name: Release Build

on:
  push:
    tags:
      - 'v*'

env:
  UNITY_VERSION: 2021.3.4f1

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Get version from tag
        id: tag_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build Windows
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: StandaloneWindows64
          buildName: ClockApp
          buildsPath: builds
          versioning: Custom
          version: ${{ steps.tag_version.outputs.VERSION }}

      - name: Zip Build
        run: |
          cd builds/StandaloneWindows64
          zip -r ../../ClockApp-Windows-${{ steps.tag_version.outputs.VERSION }}.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ClockApp-Windows-${{ steps.tag_version.outputs.VERSION }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}